---
# name: .travis.yml
# description: This file tells travis, what needs to be done.
# author: while-true-do.io
# contact: hello@while-true-do.io
# license: BSD-3-Clause
# reference: https://docs.travis-ci.com/user/customizing-the-build

language: python
python:
  - 2.7
  - 3.6

install:
  # Install test dependencies.
  - pip install six
  - pip install requests
  - pip install ordered_set
  - pip install pykickstart

script:
  - ksvalidator files/centos7-base.ks
  - ksvalidator files/centos7-kvm.ks
  - ksvalidator files/centos7-secure.ks
  - ksvalidator files/fedora29-base.ks
  - ksvalidator files/fedora29-kvm.ks
  - ksvalidator files/fedora29-secure.ks
  - ksvalidator files/fedora30-base.ks
  - ksvalidator files/fedora30-kvm.ks
  - ksvalidator files/fedora30-secure.ks

notifications:
  email:
    recipients:
      - devel@while-true-do.io
    on_success: never
    on_failure: always

  irc:
    channels:
      - "chat.freenode.net#while-true-do"
    on_success: always
    on_failure: always
